import { existsSync, mkdirSync, readFileSync, realpathSync, renameSync, writeFileSync } from "node:fs";
import { randomUUID } from "node:crypto";
import { homedir } from "node:os";
import { dirname, isAbsolute, join, resolve as resolvePath } from "node:path";
import { defaultAgentName } from "../session/local_config.js";

/** Persisted desired lifecycle for a daemon registration. */
export type DesiredState = "running" | "stopped";

/** Versioned daemon registry v2. Do not silently coerce an older shape. */
export interface DaemonEntry {
  /** Stable opaque endpoint identity. Never derived from cwd. */
  id: string;
  /** Absolute filesystem realpath captured at registration time. */
  cwd: string;
  name: string;
  desired_state: DesiredState;
  /** Epoch milliseconds. */
  created_at: number;
}

export interface DaemonRegistry {
  version: 2;
  daemons: DaemonEntry[];
}

export type RegistryErrorCode = "registry_schema_invalid" | "registry_schema_unsupported";

/**
 * A malformed or old registry is an operator-visible error, not an empty
 * registry. Treating it as empty could overwrite valid registrations on the
 * next save, which is destructive.
 */
export class RegistrySchemaError extends Error {
  constructor(
    public readonly code: RegistryErrorCode,
    message: string,
  ) {
    super(message);
    this.name = "RegistrySchemaError";
  }
}

function registryPathInternal(): string {
  const root = process.env["REMOTE_PI_HOME"] || homedir();
  return join(root, ".pi", "remote", "daemons.json");
}

function emptyRegistry(): DaemonRegistry {
  return { version: 2, daemons: [] };
}

/** Canonicalizes a supplied cwd and rejects nonexistent paths. */
export function normalizeCwd(input: string): string {
  if (!input || !input.trim()) throw new Error("cwd is required");
  let path = input.trim();
  if (path === "~") path = homedir();
  else if (path.startsWith("~/")) path = join(homedir(), path.slice(2));
  if (!isAbsolute(path)) path = resolvePath(process.cwd(), path);
  return realpathSync(path);
}

function registryError(message: string, code: RegistryErrorCode = "registry_schema_invalid"): never {
  throw new RegistrySchemaError(code, message);
}

function isOpaqueId(value: unknown): value is string {
  // UUID is generated by this registry. Accept UUID variants to keep the
  // persisted identifier opaque without coupling validation to a display form.
  return typeof value === "string" && /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value);
}

function parseEntry(value: unknown, index: number): DaemonEntry {
  if (!value || typeof value !== "object") registryError(`registry daemon[${index}] must be an object`);
  const entry = value as Record<string, unknown>;
  if (!isOpaqueId(entry["id"])) registryError(`registry daemon[${index}].id must be an opaque UUID`);
  if (typeof entry["cwd"] !== "string" || !isAbsolute(entry["cwd"]) || entry["cwd"].length === 0) {
    registryError(`registry daemon[${index}].cwd must be an absolute path`);
  }
  // A vanished cwd stays loadable long enough for supervisor reconcile to
  // remove it. Existing paths must already be their canonical realpath.
  if (existsSync(entry["cwd"]) && realpathSync(entry["cwd"]) !== entry["cwd"]) {
    registryError(`registry daemon[${index}].cwd must be a filesystem realpath`);
  }
  if (typeof entry["name"] !== "string" || entry["name"].trim().length === 0) {
    registryError(`registry daemon[${index}].name must be a non-empty string`);
  }
  if (entry["desired_state"] !== "running" && entry["desired_state"] !== "stopped") {
    registryError(`registry daemon[${index}].desired_state must be running or stopped`);
  }
  if (typeof entry["created_at"] !== "number" || !Number.isFinite(entry["created_at"]) || entry["created_at"] < 0) {
    registryError(`registry daemon[${index}].created_at must be an epoch timestamp`);
  }
  return {
    id: entry["id"],
    cwd: entry["cwd"],
    name: entry["name"].trim(),
    desired_state: entry["desired_state"],
    created_at: entry["created_at"],
  };
}

function validateRegistry(value: unknown): DaemonRegistry {
  if (!value || typeof value !== "object" || Array.isArray(value)) {
    registryError("registry root must be an object");
  }
  const root = value as Record<string, unknown>;
  if (root["version"] !== 2) {
    const code: RegistryErrorCode = root["version"] === undefined || root["version"] === 1
      ? "registry_schema_unsupported"
      : "registry_schema_invalid";
    registryError(
      `unsupported daemon registry version ${String(root["version"])}; remove or replace ~/.pi/remote/daemons.json before registering daemons`,
      code,
    );
  }
  if (!Array.isArray(root["daemons"])) registryError("registry.daemons must be an array");
  const daemons = root["daemons"].map((entry, index) => parseEntry(entry, index));
  const ids = new Set<string>();
  const cwds = new Set<string>();
  for (const entry of daemons) {
    if (ids.has(entry.id)) registryError(`registry contains duplicate id ${entry.id}`);
    if (cwds.has(entry.cwd)) registryError(`registry contains duplicate cwd ${entry.cwd}`);
    ids.add(entry.id);
    cwds.add(entry.cwd);
  }
  return { version: 2, daemons };
}

/** Missing file is empty v2; every existing file must be valid v2. */
export function loadRegistry(): DaemonRegistry {
  const path = registryPathInternal();
  if (!existsSync(path)) return emptyRegistry();
  let raw: string;
  try {
    raw = readFileSync(path, "utf8");
  } catch (error) {
    throw new RegistrySchemaError("registry_schema_invalid", `cannot read daemon registry: ${String(error)}`);
  }
  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch (error) {
    throw new RegistrySchemaError("registry_schema_invalid", `invalid daemon registry JSON: ${String(error)}`);
  }
  return validateRegistry(parsed);
}

/** Validates before atomically replacing the on-disk registry. */
export function saveRegistry(registry: DaemonRegistry): void {
  const valid = validateRegistry(registry);
  const path = registryPathInternal();
  mkdirSync(dirname(path), { recursive: true });
  const temp = `${path}.${process.pid}.${randomUUID()}.tmp`;
  try {
    writeFileSync(temp, JSON.stringify(valid, null, 2) + "\n", "utf8");
    renameSync(temp, path);
  } catch (error) {
    throw new Error(`failed to save daemon registry: ${String(error)}`);
  }
}

/** Explicit registration always starts in the desired running state. */
export function addDaemon(rawCwd: string, name?: string): DaemonEntry {
  const cwd = normalizeCwd(rawCwd);
  const registry = loadRegistry();
  if (registry.daemons.some((entry) => entry.cwd === cwd)) {
    throw new Error(`Daemon already registered for cwd: ${cwd}`);
  }
  const entry: DaemonEntry = {
    id: randomUUID(),
    cwd,
    name: name?.trim() || defaultAgentName(cwd),
    desired_state: "running",
    created_at: Date.now(),
  };
  registry.daemons.push(entry);
  saveRegistry(registry);
  return entry;
}

export function removeDaemon(id: string): { removed: boolean; cwd?: string } {
  const registry = loadRegistry();
  const index = registry.daemons.findIndex((entry) => entry.id === id);
  if (index === -1) return { removed: false };
  const [removed] = registry.daemons.splice(index, 1);
  saveRegistry(registry);
  return { removed: true, cwd: removed!.cwd };
}

/** Finds a registration by canonical cwd for external lifecycle integrations. */
export function findDaemonByCwd(rawCwd: string): DaemonEntry | undefined {
  let cwd: string;
  try {
    cwd = normalizeCwd(rawCwd);
  } catch {
    let path = rawCwd.trim();
    if (path === "~") path = homedir();
    else if (path.startsWith("~/")) path = join(homedir(), path.slice(2));
    cwd = isAbsolute(path) ? resolvePath(path) : resolvePath(process.cwd(), path);
  }
  return loadRegistry().daemons.find((entry) => entry.cwd === cwd);
}

/** Persists intended lifecycle independently from process state. */
export function setDaemonDesiredState(id: string, desiredState: DesiredState): DaemonEntry | undefined {
  const registry = loadRegistry();
  const entry = registry.daemons.find((item) => item.id === id);
  if (!entry) return undefined;
  entry.desired_state = desiredState;
  saveRegistry(registry);
  return entry;
}

/** Returns v2 entries in insertion order. */
export function listDaemons(): DaemonEntry[] {
  return loadRegistry().daemons;
}

/**
 * Backward compatible export name only. v2 deliberately has no in-place
 * migration: an old registry must be explicitly replaced by its operator.
 */
export function migrateRegistryNames(): number {
  loadRegistry();
  return 0;
}

export function registryPath(): string {
  return registryPathInternal();
}
